image: python:3.12.8-slim-bookworm


stages:
  - update_database


workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never # never run on push. only manual, schedule, etc.
    - when: always


update:
  stage: update_database
  before_script:
    - apt-get update && apt-get install -y git sqlite3
  script:
    - pip install -r requirements.txt
    - python update_database.py 2>error.log
    - grep -q "Sign in to confirm you’re not a bot." error.log && false # fail early if YouTube blocks us
    - sqlite3 matches.db "SELECT COUNT(*) FROM Matches;" > match_count.txt
    # https://stackoverflow.com/a/73394648
    - git config user.name "GitLab CI Pipeline"
    - git config user.email "gitlabcipipeline@example.com"
    - git remote rm gitlab_origin || true # force remove remote
    - git remote add gitlab_origin http://oauth2:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git # add remote 
    - git add matches.db
    - git commit --allow-empty -m "[CI] Update Database"
    - git push gitlab_origin HEAD:$CI_COMMIT_BRANCH -o ci.skip || true # allow no changes to pass
  artifacts:
    paths:
      - error.log
      - match_count.txt