# https://github.com/patrickloeber/python-github-action-template/blob/main/.github/workflows/actions.yml

name: run update_database.py

on:
  schedule:
    - cron: "0 8 */1 * *" # At 08:00 on every day-of-month.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python update_database.py

      - name: show git status and log before commit
        run: |
          git status
          git --no-pager log -p -1

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "updated database"
          
      - name: show git status and log after commit
        run: |
          git status
          git --no-pager log -p -1

      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
